nacos:
  config:
    server-addr: 127.0.0.1:28848
    auto-refresh: true

# endpoint http://localhost:8080/actuator/nacos-config
# health http://localhost:8080/actuator/health
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'